//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventory_Management_systeamEntities : DbContext
    {
        public Inventory_Management_systeamEntities()
            : base("name=Inventory_Management_systeamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbItemMaster> tbItemMasters { get; set; }
        public virtual DbSet<tbPurchase> tbPurchases { get; set; }
        public virtual DbSet<tbSale> tbSales { get; set; }
        public virtual DbSet<tbWarehouse> tbWarehouses { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
