//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSale
    {
        public int SaleId { get; set; }
        public string Sale_Item { get; set; }
        public Nullable<int> Sale_Qty { get; set; }
        public Nullable<System.DateTime> Sale_Date { get; set; }
    }
}
